// ********** AUTH **********

export const INITIAL = 'INITIAL';
export const INITIALIZE_SESSION_AND_SOCKET = 'INITIALIZE_SESSION_AND_SOCKET';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

// ********** REPORT **********
export const GET_REPORT_OF_REMAINING_WORKING_HOURS_REQUEST =
  'GET_REPORT_OF_REMAINING_WORKING_HOURS_REQUEST';
export const GET_REPORT_OF_REMAINING_WORKING_HOURS_SUCCESS =
  'GET_REPORT_OF_REMAINING_WORKING_HOURS_SUCCESS';
export const GET_REPORT_OF_REMAINING_WORKING_HOURS_OF_MONTH_BY_DAYS_REQUEST =
  'GET_REPORT_OF_REMAINING_WORKING_HOURS_OF_MONTH_BY_DAYS_REQUEST';
export const GET_REPORT_OF_REMAINING_WORKING_HOURS_OF_MONTH_BY_DAYS_SUCCESS =
  'GET_REPORT_OF_REMAINING_WORKING_HOURS_OF_MONTH_BY_DAYS_SUCCESS';
export const RECORD_CHECKINS_RESQUEST = 'RECORD_CHECKINS_RESQUEST';
export const RECORD_CHECKINS_RESQUEST_SUCCESS = 'RECORD_CHECKINS_RESQUEST_SUCCESS';
export const SET_LOADING = 'SET_LOADING';
export const GET_ADMIN_DASHOARD_CHECKIN_REPORT_REQUEST =
  'GET_ADMIN_DASHOARD_CHECKIN_REPORT_REQUEST';
export const GET_ADMIN_DASHOARD_CHECKIN_REPORT_SUCCESS =
  'GET_ADMIN_DASHOARD_CHECKIN_REPORT_SUCCESS';
export const REPORT_ERROR = 'REPORT_ERROR';
export const CLEAR_REPORT_DATA = 'CLEAR_REPORT_DATA';
export const CLEAR_ADMIN_DASHBOARD_DATA = 'CLEAR_ADMIN_DASHBOARD_DATA';

// ********** USERS **********
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const UPDATE_PERMISSION_REQUEST = 'UPDATE_PERMISSION_REQUEST';
export const UPDATE_PERMISSION_SUCCESS = 'UPDATE_PERMISSION_SUCCESS';

export const USER_ERROR = 'USER_ERROR';
export const CLEAR_USER_LIST = 'CLEAR_USER_LIST';
export const CLEAR_USER = 'CLEAR_USER';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';

// ********** CAR **********
export const GET_CAR_REQUEST = 'GET_CAR_REQUEST';
export const GET_CAR_SUCCESS = 'GET_CAR_SUCCESS';
export const GET_TOTAL_CAR_REQUEST = 'GET_TOTAL_CAR_REQUEST';
export const GET_TOTAL_CAR_SUCCESS = 'GET_TOTAL_CAR_SUCCESS';
export const GET_CAR_BY_ID_REQUEST = 'GET_CAR_BY_ID_REQUEST';
export const GET_CAR_BY_ID_SUCCESS = 'GET_CAR_BY_ID_SUCCESS';
export const CREATE_CAR_REQUEST = 'CREATE_CAR_REQUEST';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const UPDATE_CAR_REQUEST = 'UPDATE_CAR_REQUEST';
export const UPDATE_CAR_SUCCESS = 'UPDATE_CAR_SUCCESS';
export const CLEAR_CAR = 'CLEAR_CAR';
export const CLEAR_CAR_LIST = 'CLEAR_CAR_LIST';
export const CLEAR_TOTAL_CARS = 'CLEAR_TOTAL_CARS';
export const DELETE_CAR_REQUEST = 'DELETE_CAR_REQUEST';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
export const CAR_ERROR = 'CAR_ERROR';

// ********** CATEGORY **********
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_TOTAL_CATEGORY_REQUEST = 'GET_TOTAL_CATEGORY_REQUEST';
export const GET_TOTAL_CATEGORY_SUCCESS = 'GET_TOTAL_CATEGORY_SUCCESS';
export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const CLEAR_CATEGORY_LIST = 'CLEAR_CATEGORY_LIST';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

// ********** ERROR & MESSAGE **********
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
