// ********** USER **********

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

// ********** AUTH **********

export const INITIAL = 'INITIAL';
export const INITIALIZE_SESSION_AND_SOCKET = 'INITIALIZE_SESSION_AND_SOCKET';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

// ********** CAR **********
export const GET_CAR_REQUEST = 'GET_CAR_REQUEST';
export const GET_CAR_SUCCESS = 'GET_CAR_SUCCESS';
export const GET_TOTAL_CAR_REQUEST = 'GET_TOTAL_CAR_REQUEST';
export const GET_TOTAL_CAR_SUCCESS = 'GET_TOTAL_CAR_SUCCESS';
export const GET_CAR_BY_ID_REQUEST = 'GET_CAR_BY_ID_REQUEST';
export const GET_CAR_BY_ID_SUCCESS = 'GET_CAR_BY_ID_SUCCESS';
export const CREATE_CAR_REQUEST = 'CREATE_CAR_REQUEST';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const UPDATE_CAR_REQUEST = 'UPDATE_CAR_REQUEST';
export const UPDATE_CAR_SUCCESS = 'UPDATE_CAR_SUCCESS';
export const CLEAR_CAR = 'CLEAR_CAR';
export const CLEAR_CAR_LIST = 'CLEAR_CAR_LIST';
export const CLEAR_TOTAL_CARS = 'CLEAR_TOTAL_CARS';
export const DELETE_CAR_REQUEST = 'DELETE_CAR_REQUEST';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
export const CAR_ERROR = 'CAR_ERROR';

// ********** CATEGORY **********
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_TOTAL_CATEGORY_REQUEST = 'GET_TOTAL_CATEGORY_REQUEST';
export const GET_TOTAL_CATEGORY_SUCCESS = 'GET_TOTAL_CATEGORY_SUCCESS';
export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const CLEAR_CATEGORY_LIST = 'CLEAR_CATEGORY_LIST';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

// ********** ERROR & MESSAGE **********
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
